Сравнение алгоритмов

* генерация тестовых данных
  настоящие vs синтетичесике данны
  настоящие
    * дорого сделать
    * содержат ошибки
    * сильно отличаются друг от друга(нет двух наборов данных,
      отличающихся по одному параметру)
    * нет общего формата данных
  синтетичесике
    * просто сделать
    * можно моделировать ошибки
    * можно смотреть на крайние случаи
    * можно сгенерировать данные, выходящие за границы модели
  В результате решили использовать синтетические данные, но
  дополнительно сверефицироваться на настоящих (192 кошки).

  Синтетические данные, вообще говоря, получаются из модели. Т.е, в
  реальной жизни есть кошки, они как-то скрешиваются, и мы наблюдаем
  генотипы. Т.е процесс порождает генотипы.

  соответственно in silico мы, на самом деле, моделируем не генотипы,
  а процесс, их порождающий.

  Можно моделировать настоящий процесс, можно моделировать процесс
  без кратных кроссинговеров, можно моделировать процесс с
  неправильной информацией о предках. Ну и просто скармливать тулзам
  мусор, чтобы проверить, что они совсем уж не врут.

  Схема моделирования --- есть несколько особей прародителей,
  генерируем поколения, симулируя кроссинговер. Параеметры модели --
  как выбирать родителей и как делать кроссинговеры.

* процесс сравнения и анализа
  Нагенерить датасетов с разными параметрами (интереснее всего
  кроссинговер) и запустить три тулза на них. Есть предположение что
  при малой частот кроссинговера между двумя соседними маркерами
  алгоритм ССС будет точным и быстрым, будет супер точным, если
  запретить кратные кроссинговеры. Можно, наверное, "завалить"
  алгоритм сысоева, если будут очень частые кроссинговеры.

  Платформа проверки... ОС линупс, 4 треда, 4 гига оперативки. Можно
  мотивировать это тем, что другие алгоритмы экспоненциальные, и
  увеличивать ресурсы не имеет смысла (2х CPU == + 1 кошка).

  В результате анализа, выяснено, что алгоритм сысоева корректно
  воссстанавливает расстояния, когда они маленьие, и не очень, когда
  они большие. Однако их можно точно восстановить, посмотрев на
  остовные деревься и прочую лабуду про маленькие расстояния. При
  этом время работы квадрат +/, что хорошо.

* обобщённые данные
  Щито это?
  Проверка на реальных данных(есть вариант придумать что нить кроме
  кошек?) показала, что алгоритм ССС работает ОЦК.
